version: "3.9"
services:
  shippigngs:
    ports:
      - 3001:3001
    build:
      context: ./db
      args:
        - route=shippings
        - port=3001
    volumes:
      - ./db:/db
  payments:
    ports:
      - 3002:3002
    build:
      context: ./db
      args:
        - route=payments
        - port=3002
    volumes:
      - ./db:/db
